### ISSUE TITLE
How does it compare to GeoRedis?

### ISSUE THREAD

**Issue by jgamedev** [strikeentco/geo-nearby#2]
Hi,

Thank you for sharing this software.
I'd be interested to know how does it compare with other solutions such as https://github.com/arjunmehta/node-georedis in terms of speed, system resource usage and scalability?

Cheers.

**Comment by strikeentco** [comment]
Hello, thank you for the question.

This library were originaly inspired by [geo-proximity](https://github.com/arjunmehta/node-geo-proximity). `geo-proximity` was wonderful but I needed something, which works without DB, so I decided to port `geo-proximity` for work with memory only.
This library stores all data in memory, so this is good and bad at the same time. This is good because it fast, this is bad because it takes a lot of memory (depends on data size).
To minimize memory usage it's recommended to use default data syntax or use `.createCompactSet` method.

Unlike `geo-proximity` and `geo-redis` (which is _async_ libs), this library is _sync_ so it's may be sometimes bad (in the future I'll add async methods).

If data set is _sorted_, this library works _really fast_.
For example: I use `geo-nearby` on my site, where this library searching in file with **_208000 locations_**.
This code is executed for **3ms**:

``` js
const geo = new Geo(geoSet, { sorted: true });
geo.limit(1).nearBy(-18.96, 32.66, 100000); // limit(1)
```

This code is executed for **4ms**:

``` js
const geo = new Geo(geoSet, { sorted: true });
geo.limit(0).nearBy(-18.96, 32.66, 100000); // no limits
```

This code is executed for **7ms**:

``` js
const geo = new Geo(geoSet, { sorted: true });
geo.limit(1).nearBy(-18.96, 32.66, [250, 100000]); // limit(1) + a range of distances
```

This code is executed for **10ms**:

``` js
const geo = new Geo(geoSet, { sorted: true });
geo.limit(0).nearBy(-18.96, 32.66, [250, 100000]); // no limits + a range of distances
```

In the examples below, it's considered _the worst case_, when the desired entry at the end of the file and data set is _unsorted_.
This code is executed for **10ms**:

``` js
const geo = new Geo(geoSet);
geo.limit(1).nearBy(-18.96, 32.66, 100000); // limit(1)
```

This code is executed for **17ms**:

``` js
const geo = new Geo(geoSet);
geo.limit(0).nearBy(-18.96, 32.66, 100000); // no limits
```

This code is executed for **38ms**:

``` js
const geo = new Geo(geoSet);
geo.limit(1).nearBy(-18.96, 32.66, [250, 100000]); // limit(1) + a range of distances
```

This code is executed for **99ms**:

``` js
const geo = new Geo(geoSet);
geo.limit(0).nearBy(-18.96, 32.66, [250, 100000]); // no limits + a range of distances
```

**Comment by jgamedev** [comment]
Hey Alexey, 
Thank you for you taking the time answer this so thoroughly  (maybe add some of this info to the read me for others considering this package in the future?)
I suspect it would not be hard to re-structure it in a way that doesn't block the process execution.. maybe by leveraging Node's process.fork() capabilities?

Thanks again and hopefully I'll  find some time to try this package in the coming days. Cheers!
